import { useState, useEffect, useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { BookOpen, ChevronDown, Play } from 'lucide-react'
import { useNavigate, useLocation } from 'react-router-dom'
import { useDashboard } from '../context/DashboardContext'
import { useToast } from '../context/ToastContext'
import { useAccentTheme } from '../hooks/useAccentTheme'
import { curriculumApi, syllabusApi } from '../services/api'
import type { ModuleDto, Py4eCurriculumPayload } from '../services/api'

function normalizeSyllabus(data: unknown): { track: string; total_modules: number; estimated_weeks: number; modules: ModuleDto[] } {
  const raw = (data as { syllabus?: unknown; modules?: ModuleDto[] })?.syllabus ?? (data as { modules?: ModuleDto[] })?.modules ?? data
  const arr = Array.isArray(raw) ? raw : (raw as { modules?: ModuleDto[] })?.modules ?? []
  return {
    track: (data as { track?: string })?.track ?? 'Python Foundations',
    total_modules: (data as { total_modules?: number })?.total_modules ?? arr.length,
    estimated_weeks: (data as { estimated_weeks?: number })?.estimated_weeks ?? 4,
    modules: arr as ModuleDto[],
  }
}

export default function DashboardSyllabus() {
  const { accentPrimary, accentSecondary } = useAccentTheme()
  const { syllabusModules, setSyllabusModules, fullPlacementResult, placementId } = useDashboard()
  const { addToast } = useToast()
  const navigate = useNavigate()
  const location = useLocation()
  const [loading, setLoading] = useState(false)
  const [expandedId, setExpandedId] = useState<string | null>(null)
  const autoGenerateDone = useRef(false)
  const [lastError, setLastError] = useState<string | null>(null)
  const [py4eOutline, setPy4eOutline] = useState<Py4eCurriculumPayload | null>(null)
  const [outlineOpen, setOutlineOpen] = useState(false)
  const [outlineChapter, setOutlineChapter] = useState<string | null>(null)

  const hasSyllabus = syllabusModules.length > 0

  useEffect(() => {
    let cancelled = false
    curriculumApi
      .getPy4e()
      .then((data) => {
        if (!cancelled) setPy4eOutline(data)
      })
      .catch(() => {
        /* optional reference — ignore if API down */
      })
    return () => {
      cancelled = true
    }
  }, [])

  useEffect(() => {
    const auto = (location.state as { autoGenerate?: boolean })?.autoGenerate
    if (auto && fullPlacementResult && !hasSyllabus && !autoGenerateDone.current) {
      autoGenerateDone.current = true
      handleGenerate()
    }
  }, [fullPlacementResult, hasSyllabus])

  const handleGenerate = async () => {
    const placement = fullPlacementResult ?? (() => {
      try {
        const s = localStorage.getItem('placement_result')
        return s ? JSON.parse(s) : null
      } catch {
        return null
      }
    })()
    if (!placement || !placementId) {
      addToast('error', 'Complete the placement test first.')
      navigate('/dashboard/placement')
      return
    }
    setLoading(true)
    setLastError(null)
    try {
      const trackRaw = String((placement as { track?: string })?.track ?? 'python').toLowerCase().replace(/_/g, '-')
      const trackLabel = trackRaw.includes('deep') ? 'Deep Learning' : 'Python'
      const courseTitle = `${trackLabel} ${String(placement.level).replace(/_/g, ' ')} Course`
      const data = await syllabusApi.generate(placementId, courseTitle)
      const envelope = data as { result?: { syllabus?: ModuleDto[]; modules?: ModuleDto[]; track?: string }; syllabus?: ModuleDto[]; modules?: ModuleDto[] }
      const resolved = envelope.result ?? envelope
      if ((resolved as any)?.status === 'error' && (resolved as any)?.error) {
        const msg = String((resolved as any).error)
        setLastError(msg)
        addToast('error', `Generation failed: ${msg}`)
        return
      }
      const normalized = normalizeSyllabus(resolved)
      if (normalized.modules.length) {
        setSyllabusModules(normalized.modules)
        addToast('success', 'Syllabus generated! 🎉')
      } else {
        const msg = 'Syllabus generator returned an empty plan.'
        setLastError(msg)
        addToast('error', msg)
      }
    } catch (err) {
      const anyErr = err as any
      const apiMsg = anyErr?.response?.data?.error
      const msg = apiMsg ? `Generation failed: ${String(apiMsg)}` : 'Failed to generate. Please try again.'
      setLastError(msg)
      addToast('error', msg)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div
      className="flex-1 min-w-0 overflow-y-auto p-6"
      style={{ backgroundColor: 'var(--bg-primary)' }}
    >
      <div className="max-w-4xl mx-auto">
        {py4eOutline && (
          <div
            className="mb-6 rounded-2xl border overflow-hidden"
            style={{ borderColor: 'var(--border-color)', backgroundColor: 'var(--bg-card)' }}
          >
            <button
              type="button"
              className="w-full flex items-center justify-between gap-3 p-4 text-left hover:bg-white/5"
              onClick={() => setOutlineOpen((o) => !o)}
            >
              <div>
                <p className="text-xs font-medium text-[color:var(--text-muted)]">Reference — Python for Everybody</p>
                <p className="text-sm font-semibold text-[color:var(--text-primary)]">
                  Book tracks and chapter sub-lessons (TOC)
                </p>
              </div>
              <ChevronDown className={`h-5 w-5 text-slate-400 shrink-0 transition-transform ${outlineOpen ? 'rotate-180' : ''}`} />
            </button>
            {outlineOpen && (
              <div className="border-t px-4 pb-4 space-y-4 max-h-[min(70vh,520px)] overflow-y-auto" style={{ borderColor: 'var(--border-color)' }}>
                {py4eOutline.tracks.map((t) => (
                  <div key={t.id}>
                    <p className="text-sm font-semibold text-[color:var(--text-primary)] mt-3">
                      {t.label_en} <span className="text-[color:var(--text-muted)] font-normal">({t.label_ar})</span>
                    </p>
                    <p className="text-xs text-[color:var(--text-secondary)] mb-2">{t.goal_ar}</p>
                    <ul className="space-y-1">
                      {t.chapter_keys.map((ck) => {
                        const ch = py4eOutline.chapters[ck]
                        if (!ch) return null
                        const open = outlineChapter === ck
                        return (
                          <li key={ck} className="rounded-lg border" style={{ borderColor: 'var(--border-color)' }}>
                            <button
                              type="button"
                              className="w-full text-left px-3 py-2 text-xs flex items-center justify-between gap-2 hover:bg-white/5"
                              onClick={() => setOutlineChapter(open ? null : ck)}
                            >
                              <span className="text-[color:var(--text-primary)] font-medium">
                                Ch {ch.number}: {ch.title}
                              </span>
                              <ChevronDown className={`h-4 w-4 shrink-0 ${open ? 'rotate-180' : ''}`} />
                            </button>
                            {open && (
                              <ol className="list-decimal pl-8 pr-2 pb-2 space-y-0.5 text-[11px] text-[color:var(--text-secondary)]">
                                {ch.sub_lessons.map((s) => (
                                  <li key={s.id}>
                                    <span className="text-[color:var(--text-muted)]">{s.id}</span> {s.title}
                                  </li>
                                ))}
                              </ol>
                            )}
                          </li>
                        )
                      })}
                    </ul>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        <div className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-bold text-[color:var(--text-primary)]">My Syllabus</h1>
          <button
            type="button"
            onClick={handleGenerate}
            disabled={loading || !fullPlacementResult}
            className="rounded-xl py-2.5 px-4 text-sm font-semibold text-white flex items-center gap-2 disabled:opacity-60"
            style={{
              background: `linear-gradient(90deg, ${accentPrimary}, ${accentSecondary})`,
            }}
          >
            <BookOpen className="h-4 w-4" />
            {loading ? 'Generating…' : hasSyllabus ? 'Regenerate Syllabus' : 'Generate Syllabus'}
          </button>
        </div>

        {loading && (
          <div
            className="rounded-2xl border p-12 text-center py-16"
            style={{ borderColor: 'var(--border-color)', backgroundColor: 'var(--bg-card)' }}
          >
            <div
              className="animate-spin h-12 w-12 border-2 border-t-transparent rounded-full mx-auto mb-4"
              style={{ borderColor: accentPrimary }}
            />
            <p className="text-[color:var(--text-primary)] font-medium mb-1">
              Syllabus Agent is building your personalized path…
            </p>
            <p className="text-sm text-[color:var(--text-muted)]">Analyzing your placement results…</p>
          </div>
        )}

        {!hasSyllabus && !loading && (
          <div
            className="rounded-2xl border-2 border-dashed p-12 text-center"
            style={{ borderColor: 'var(--border-color)', backgroundColor: 'var(--bg-card)' }}
          >
            <BookOpen className="h-12 w-12 mx-auto text-slate-500 mb-4" />
            <p className="text-[color:var(--text-secondary)] mb-4">
              No syllabus yet. Complete the placement test and generate your personalized learning path.
            </p>
            {lastError && (
              <p className="text-sm text-rose-400 mb-4 whitespace-pre-wrap">
                {lastError}
              </p>
            )}
            <button
              type="button"
              onClick={handleGenerate}
              disabled={!fullPlacementResult}
              className="rounded-xl py-3 px-6 text-white font-semibold disabled:opacity-60"
              style={{
                background: `linear-gradient(90deg, ${accentPrimary}, ${accentSecondary})`,
              }}
            >
              {lastError ? '🔄 Try Again' : 'Generate Syllabus'}
            </button>
          </div>
        )}

        {hasSyllabus && (
          <div className="space-y-3">
            {syllabusModules.map((module) => {
              const isExpanded = expandedId === module.module_id
              return (
                <motion.div
                  key={module.module_id}
                  layout
                  className="rounded-2xl overflow-hidden"
                  style={{
                    backgroundColor: 'var(--bg-card)',
                    border: '1px solid var(--border-color)',
                  }}
                >
                  <button
                    type="button"
                    className="w-full flex items-center gap-3 p-4 text-left hover:bg-white/5 transition-colors"
                    onClick={() => setExpandedId(isExpanded ? null : module.module_id)}
                  >
                    <ChevronDown className={`h-5 w-5 text-slate-400 shrink-0 transition-transform ${isExpanded ? 'rotate-180' : ''}`} />
                    <div className="flex-1 min-w-0">
                      <span className="text-xs font-medium text-[color:var(--text-muted)]">
                        Unit {syllabusModules.indexOf(module) + 1}
                      </span>
                      <h2 className="text-lg font-semibold text-[color:var(--text-primary)]">
                        {module.title}
                      </h2>
                      <div className="flex flex-wrap gap-2 mt-1 text-xs text-[color:var(--text-muted)]">
                        {(module as any)?.estimated_hours != null && (
                          <span>{Number((module as any).estimated_hours)}h</span>
                        )}
                        <span>{(module as any).difficulty ?? module.target_level}</span>
                        <span>{module.lessons?.length ?? 0} lessons</span>
                      </div>
                      {(module as any)?.description && (
                        <p className="text-sm text-[color:var(--text-secondary)] mt-1">
                          {(module as any).description}
                        </p>
                      )}
                    </div>
                    <div className="h-2 flex-1 max-w-[120px] rounded-full bg-slate-700 overflow-hidden">
                      <div
                        className="h-full rounded-full bg-emerald-500"
                        style={{ width: '0%' }}
                      />
                    </div>
                  </button>
                  <AnimatePresence>
                    {isExpanded && module.lessons && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        className="border-t overflow-hidden"
                        style={{ borderColor: 'var(--border-color)' }}
                      >
                        <div className="p-4 pt-2 space-y-3">
                          {module.lessons.map((lesson) => (
                            <div
                              key={lesson.lesson_id}
                              className="rounded-xl border border-white/5 overflow-hidden"
                              style={{ backgroundColor: 'var(--bg-primary)' }}
                            >
                              <div className="flex items-center justify-between gap-3 py-2 px-3 hover:bg-white/5 lesson-item">
                                <div className="min-w-0 flex-1">
                                  <p className="text-sm font-medium text-[color:var(--text-primary)]">
                                    {lesson.title}
                                  </p>
                                  <div className="flex flex-wrap items-center gap-2 mt-0.5">
                                    <span className="text-[10px] text-[color:var(--text-muted)]">{lesson.topic}</span>
                                    {(lesson as any)?.duration_minutes != null && (
                                      <span className="text-[10px] text-[color:var(--text-muted)]">
                                        {Number((lesson as any).duration_minutes)} min
                                      </span>
                                    )}
                                    {lesson.sub_lessons?.length ? (
                                      <span className="text-[10px] text-sky-300/90">
                                        {lesson.sub_lessons.length} focused parts
                                      </span>
                                    ) : null}
                                  </div>
                                </div>
                                <span className="text-[10px] px-2 py-0.5 rounded bg-slate-700 text-slate-300 type-badge shrink-0">
                                  {(lesson as { type?: string }).type ?? 'Lesson'}
                                </span>
                                <button
                                  type="button"
                                  onClick={() => navigate('/dashboard/lessons', { state: { lesson } })}
                                  className="shrink-0 rounded-lg py-1.5 px-3 text-xs font-semibold text-white flex items-center gap-1"
                                  style={{
                                    background: `linear-gradient(135deg, ${accentPrimary}, ${accentSecondary})`,
                                  }}
                                >
                                  Start <Play className="h-3 w-3" />
                                </button>
                              </div>
                              {lesson.sub_lessons?.length ? (
                                <ul className="border-t border-white/5 px-3 py-2 space-y-1.5" style={{ borderColor: 'var(--border-color)' }}>
                                  {lesson.sub_lessons.map((sub, si) => (
                                    <li
                                      key={sub.lesson_id}
                                      className="flex items-center justify-between gap-2 text-xs text-[color:var(--text-secondary)]"
                                    >
                                      <span className="min-w-0 truncate">
                                        <span className="text-sky-400 font-medium">Part {si + 1}</span>{' '}
                                        {sub.title}
                                      </span>
                                      <button
                                        type="button"
                                        onClick={() => navigate('/dashboard/lessons', { state: { lesson: sub } })}
                                        className="shrink-0 rounded-md py-1 px-2 text-[10px] font-semibold text-white"
                                        style={{
                                          background: `linear-gradient(135deg, ${accentPrimary}, ${accentSecondary})`,
                                        }}
                                      >
                                        Start
                                      </button>
                                    </li>
                                  ))}
                                </ul>
                              ) : null}
                            </div>
                          ))}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>
              )
            })}
          </div>
        )}
      </div>
    </div>
  )
}
